services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_USER: docker
      MYSQL_PASSWORD: dockerpassword
      MYSQL_DATABASE: rest-with-spring-boot
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    expose:
      - "3306"
    networks:
      - jb-network

  rest-with-spring-boot:
    image: jonathanbeskow99/rest-with-spring-boot
    restart: always
    build:
      context: ./16-RestWithSpringBootUdemy-Files
      dockerfile: Dockerfile
    working_dir: /16-RestWithSpringBootUdemy-Files
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rest-with-spring-boot?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: dockerpassword
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - jb-network

networks:
  jb-network:
    driver: bridge
